config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  resources :live_aboards
  
  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

end

app/models/live_aboard.rb
class LiveAboard < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/live_aboards_controller.rb
class LiveAboardsController < ApplicationController
  before_action :set_live_aboard, only: [:show, :edit, :update, :destroy]

  # GET /live_aboards
  # GET /live_aboards.json
  def index
    @live_aboards = LiveAboard.all
  end

  # GET /live_aboards/1
  # GET /live_aboards/1.json
  def show
  end

  # GET /live_aboards/new
  def new
    @live_aboard = LiveAboard.new
  end

  # GET /live_aboards/1/edit
  def edit
  end

  # POST /live_aboards
  # POST /live_aboards.json
  def create
    @live_aboard = LiveAboard.new(live_aboard_params)

    respond_to do |format|
      if @live_aboard.save
        format.html { redirect_to @live_aboard, notice: 'Live aboard was successfully created.' }
        format.json { render :show, status: :created, location: @live_aboard }
      else
        format.html { render :new }
        format.json { render json: @live_aboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_aboards/1
  # PATCH/PUT /live_aboards/1.json
  def update
    respond_to do |format|
      if @live_aboard.update(live_aboard_params)
        format.html { redirect_to @live_aboard, notice: 'Live aboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @live_aboard }
      else
        format.html { render :edit }
        format.json { render json: @live_aboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_aboards/1
  # DELETE /live_aboards/1.json
  def destroy
    @live_aboard.destroy
    respond_to do |format|
      format.html { redirect_to live_aboards_url, notice: 'Live aboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live_aboard
      @live_aboard = LiveAboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def live_aboard_params
      params.require(:live_aboard).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/live_aboards_helper.rb
module LiveAboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<p>Copyright LiveAboard</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "LiveAboard", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %> <span class="sr-only">(current)</span></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/bootstrap' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  
  <div class="container-fluid">
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/live_aboards/_form.html.erb
<%= form_for(@live_aboard, :html => { multipart: true }) do |f| %>
  <% if @live_aboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@live_aboard.errors.count, "error") %> prohibited this live_aboard from being saved:</h2>

      <ul>
      <% @live_aboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/live_aboards/edit.html.erb
<h1>Editing Live Aboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @live_aboard, class: "btn btn-link" %> |
<%= link_to 'Back', live_aboards_path, class: "btn btn-link" %>

app/views/live_aboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Live Aboards</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @live_aboards.each do |live_aboard| %>
      <tr>
        <td><%= live_aboard.name %></td>
        <td><%= live_aboard.address %></td>
        <td><%= live_aboard.phone %></td>
        <td><%= live_aboard.website %></td>
        <td><%= link_to 'Show', live_aboard, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_live_aboard_path(live_aboard), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', live_aboard, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Live aboard', new_live_aboard_path, class: "btn btn-link" %>

app/views/live_aboards/new.html.erb
<h1>New Live Aboard</h1>

<%= render 'form' %>

<%= link_to 'Back', live_aboards_path, class: "btn btn-link" %>

app/views/live_aboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @live_aboard.image_url %>

<p>
  <strong>Name:</strong>
  <%= @live_aboard.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @live_aboard.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @live_aboard.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @live_aboard.website %>
</p>

<%= link_to 'Edit', edit_live_aboard_path(@live_aboard), class: "btn btn-link" %> |
<%= link_to 'Back', live_aboards_path, class: "btn btn-link" %>

app/views/pages/about.html.erb
<h1>Welcome to LiveAboard Reviews!</h1>
<h2>Discover the scuba diving vacation best for you -- and discover the best boat for it, too!</h2>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Contact us at test@example.com</p>

app/views/pages/home.html.erb
<h1>Welcome to LiveAboard!</h1>